# Generated by Django 5.0.7 on 2024-08-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_alter_ticket_options_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="reading_time",
            field=models.PositiveIntegerField(default=0, verbose_name="زمان مطالعه"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comment",
            name="active",
            field=models.BooleanField(default=False, verbose_name="اکتیو"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=models.TextField(verbose_name="text"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="name",
            field=models.CharField(max_length=250, verbose_name="name"),
        ),
    ]
