# Generated by Django 5.0.7 on 2024-08-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_alter_image_image_file_alter_image_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("تکنولوژی", "تکنولوی"),
                    ("زبان برنامه نویسی", "زبان برنامه نویسی"),
                    ("هوش مصنوعی", "هوش مصنوعی"),
                    ("بلاکچین", "بلاکچین"),
                    ("سایر", "سایر"),
                ],
                default="سایر",
                max_length=20,
                verbose_name="دسته بندی",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("DF", "Draft"), ("PB", "Published"), ("RJ", "Rejected")],
                default="DF",
                max_length=2,
                verbose_name="وضعیت",
            ),
        ),
    ]
