# Generated by Django 5.0.7 on 2024-08-26 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0011_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=models.TextField(verbose_name="متن"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="name",
            field=models.CharField(max_length=250, verbose_name="اسم"),
        ),
        migrations.AlterField(
            model_name="image",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="توضیحات"),
        ),
        migrations.AlterField(
            model_name="image",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="blog.post",
                verbose_name="پست",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="title",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="اسم"
            ),
        ),
    ]
