# Generated by Django 5.0.7 on 2024-08-26 00:18

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0012_alter_comment_body_alter_comment_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="created",
            field=django_jalali.db.models.jDateTimeField(
                auto_now_add=True, verbose_name="تاریخ ایجاد"
            ),
        ),
    ]
