# Generated by Django 5.0.7 on 2024-08-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0013_alter_image_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("DF", "Draft"), ("PB", "Published"), ("RJ", "Rejected")],
                default="DF",
                max_length=2,
                verbose_name="وضعیت پست",
            ),
        ),
    ]
