# Generated by Django 5.0.7 on 2024-09-03 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0014_alter_post_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-created"],
                "verbose_name": "پست",
                "verbose_name_plural": "پست ها",
            },
        ),
        migrations.RemoveIndex(
            model_name="post",
            name="blog_post_publish_bb7600_idx",
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["-created"], name="blog_post_created_76eb4c_idx"
            ),
        ),
    ]
