# Generated by Django 6.1 on 2026-08-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='وضعیت اکانت (فعال/غیرفعال)'),
        ),
    ]
