# Generated by Django 6.1 on 2026-09-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_account_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('اخبار تکنولوژی', 'اخبار تکنولوژی'), ('مصاحبه', 'مصاحبه'), ('هوش مصنوعی', 'هوش مصنوعی'), ('نئولرنینگ', 'نئولرنینگ'), ('دورنگاه', 'دورنگاه'), ('مقاله های علمی', 'مقاله های علمی'), ('سرگرمی', 'سرگرمی'), ('پادکست', 'پادکست'), ('سایر', 'سایر')], default='سایر', max_length=20, verbose_name='دسته بندی'),
        ),
    ]
